import { Metadata } from "next";
import { ChartAreaInteractive } from "@/components/chart-area-interactive";
import { SectionCards } from "@/components/section-cards";

export const metadata: Metadata = {
  title: "Overview | ViralReply",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="flex flex-col gap-4 md:gap-6 md:py-6">
      <SectionCards />
      <div className="px-4 lg:px-6">
        <ChartAreaInteractive />
      </div>
    </div>
  );
}
